"""add judge option

Revision ID: 0ad6131d9337
Revises: ce70c7595ec6
Create Date: 2025-06-28 22:23:53.605778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad6131d9337'
down_revision = 'ce70c7595ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_judge_id_judges', 'judges', ['judge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('judge_id')

    # ### end Alembic commands ###
