"""Describe your change here

Revision ID: 58aa8a554656
Revises: 
Create Date: 2025-05-05 01:16:34.450084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58aa8a554656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_last_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('emergency_contact_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('emergency_contact_last_name')
        batch_op.drop_column('emergency_contact_first_name')

    # ### end Alembic commands ###
