"""added judge id

Revision ID: 6f3cd07c711a
Revises: 0ad6131d9337
Create Date: 2025-07-11 13:33:32.080805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3cd07c711a'
down_revision = '0ad6131d9337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_judge_id_judges'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tournament_signups_judge_id_user', 'user', ['judge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_signups_judge_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_judge_id_judges'), 'judges', ['judge_id'], ['id'])

    # ### end Alembic commands ###
