"""User Event active col

Revision ID: 816d99648905
Revises: d3c762ffbeb2
Create Date: 2025-08-07 16:40:26.071096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816d99648905'
down_revision = 'd3c762ffbeb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__event', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
