"""Add Tournament_Partners model

Revision ID: 8453e55c1962
Revises: a0300480cf19
Create Date: 2025-08-17 23:22:07.859717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8453e55c1962'
down_revision = 'a0300480cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Tournament_Partners table
    op.create_table('tournament__partners',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('partner1_user_id', sa.Integer(), nullable=False),
        sa.Column('partner2_user_id', sa.Integer(), nullable=False),
        sa.Column('tournament_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
        sa.ForeignKeyConstraint(['partner1_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['partner2_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop Tournament_Partners table
    op.drop_table('tournament__partners')

    # ### end Alembic commands ###
