"""Add partner event support

Revision ID: a0300480cf19
Revises: 7a522f566f44
Create Date: 2025-08-17 23:18:56.590601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0300480cf19'
down_revision = '7a522f566f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tournament_signups_partner_id', 'user', ['partner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_signups_partner_id', type_='foreignkey')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
