"""Add Event_Leader model for multiple event leaders

Revision ID: a86e3b5c0bea
Revises: f9g8h7i6j5k4
Create Date: 2025-09-27 19:33:09.499952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86e3b5c0bea'
down_revision = 'f9g8h7i6j5k4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The event_leader table already exists, just migrate data
    op.execute('INSERT INTO event__leader (event_id, user_id) SELECT id, owner_id FROM event WHERE owner_id IS NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove migrated data
    op.execute('DELETE FROM event__leader')

    # ### end Alembic commands ###
