"""added is_going

Revision ID: ce70c7595ec6
Revises: d03ef3e0538d
Create Date: 2025-06-17 14:53:41.585885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce70c7595ec6'
down_revision = 'd03ef3e0538d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_going', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament__signups', schema=None) as batch_op:
        batch_op.drop_column('is_going')

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
