"""added child

Revision ID: d03ef3e0538d
Revises: 58aa8a554656
Create Date: 2025-05-20 13:14:14.554800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03ef3e0538d'
down_revision = '58aa8a554656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('child_last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('child_last_name')
        batch_op.drop_column('child_first_name')

    # ### end Alembic commands ###
